### ISSUE TITLE
Something works wrong

### ISSUE THREAD

**Issue by dslpp056193** [haensl/gulp-embed-svg#16]
It cuts all after svg embed.

Before:

![image](https://user-images.githubusercontent.com/11080873/57308559-447c4400-70ef-11e9-9a47-8c61399d8b58.png)

After:

![image](https://user-images.githubusercontent.com/11080873/57308579-4cd47f00-70ef-11e9-897f-576171d7f231.png)

Gulp:

![image](https://user-images.githubusercontent.com/11080873/57308627-6249a900-70ef-11e9-993f-e0331caed4bc.png)

**Comment by dslpp056193** [comment]
It tries to find closing tag. If i use paired tag (svg or [omg] img as a paired tag), all works fine.

**Comment by haensl** [comment]
Hi!

Thank you for reporting this issue. The behaviour you observe is indeed the result of feeding the non-closed `<img>` tag to [htmlparser2](https://github.com/fb55/htmlparser2/wiki/Parser-options) with the [`xmlMode`](https://github.com/fb55/htmlparser2/wiki/Parser-options#option-xmlmode) option deployed. We use `xmlMode` in gulp-embed-svg in order to parse various SVG attributes, tags and properties correctly.

Once you adjust your image tag to close, your code will work, e.g. change line 36 in your source file to
```html
<img src="./img/icons/icon.svg" alt="" /> <!-- NOTICE THE closing slash -->
```
your code should work fine.

I have, created a [pull request introducing unit tests to verify that self-closing and non-closing img tags work.](https://github.com/haensl/gulp-embed-svg/pull/17). Please go ahead and check it out.
